# Generated by Django 4.2 on 2023-04-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='perrson',
        ),
    ]
